### ISSUE TITLE
Outgoing Link

### ISSUE THREAD

**Issue by ghost** [CarletonComputerScienceSociety/website-2014#22]
Pressing continue does nothing, neither does return.
ex. http://ccss.carleton.ca/forums/topic/17/wiki

**Comment by Sqash** [comment]
Can you thoroughly elaborate on your problem? I can't attempt to reproduce the error with this little info. Add screenshots as well if relevant please.

**Comment by ghost** [comment]
http://ccss.carleton.ca/forums/topic/17/wiki

> click imgur link

![ss 2015-09-23 at 01 37 50](https://cloud.githubusercontent.com/assets/11600379/10038512/0e0bdf42-6195-11e5-9e81-2f87dce5b78d.png)

I think the server is treating the continue link the same as it treats any other external link posted in the forum. So it keeps redirecting to itself infinitely.

> after mashing continue link

![ss 2015-09-23 at 01 45 27](https://cloud.githubusercontent.com/assets/11600379/10038513/12ab84e4-6195-11e5-9e7e-6ccae9af8e11.png)

**Comment by Sqash** [comment]
Thanks, we'll look into it. Unfortunately though, it may be a problem with the most recent release of NodeBB (which is what the forum is running). Hopefully it should be fixed soon.
